class URLs:
    url = 'https://www.saucedemo.com/v1/'
    auth_url = 'https://www.saucedemo.com/v1/index.html'
    exp_title = 'Sauce Labs: Cross Browser Testing, Selenium Testing & Mobile Testing'
    inventory_url = 'https://www.saucedemo.com/v1/inventory.html'
    about_url = 'https://saucelabs.com/'
    cart_url = 'https://www.saucedemo.com/v1/cart.html'
    checkout_url = 'https://www.saucedemo.com/v1/checkout-step-one.html'
    confirm_url = 'https://www.saucedemo.com/v1/checkout-step-two.html'
    complete_url = 'https://www.saucedemo.com/v1/checkout-complete.html'
    item_url_1 = 'https://www.saucedemo.com/v1/inventory-item.html?id=4'
    item_url_2 = 'https://www.saucedemo.com/v1/inventory-item.html?id=0'
    item_url_3 = 'https://www.saucedemo.com/v1/inventory-item.html?id=1'
    item_url_4 = 'https://www.saucedemo.com/v1/inventory-item.html?id=5'
    item_url_5 = 'https://www.saucedemo.com/v1/inventory-item.html?id=2'
    item_url_6 = 'https://www.saucedemo.com/v1/inventory-item.html?id=3'

